apiVersion: v1
kind: ConfigMap
metadata:
  name: nr-demo-config
  namespace: nr-demo
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "nrdemo"
  POSTGRES_USER: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  USER_SERVICE_URL: "http://user-service:8001"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  CART_SERVICE_URL: "http://cart-service:4001"
  ORDER_SERVICE_URL: "http://order-service:8081"
  CHAT_SERVICE_URL: "http://ai-chat-service:8002"
  ADMIN_SERVICE_URL: "http://admin-service:8003"
  NEW_RELIC_CLUSTER_NAME: "nr-demo-minikube"
