apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: nr-demo
spec:
  replicas: 1
  selector:
    matchLabels: { app: cart-service }
  template:
    metadata:
      labels: { app: cart-service }
    spec:
      containers:
        - name: cart-service
          image: nr-demo/cart-service:latest
          imagePullPolicy: Never
          ports: [{ containerPort: 4001 }]
          envFrom:
            - configMapRef: { name: nr-demo-config }
          env:
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom: { secretKeyRef: { name: nr-demo-secrets, key: NEW_RELIC_LICENSE_KEY } }
            - name: NEW_RELIC_APP_NAME
              value: "NR-Demo-Cart-Service"
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: nr-demo-secrets, key: JWT_SECRET } }
          readinessProbe:
            httpGet: { path: /health, port: 4001 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { memory: "128Mi", cpu: "50m" }
            limits:   { memory: "256Mi", cpu: "500m" }
